"""Fix password

Revision ID: 378ccfd8c886
Revises: 3bc4df442391
Create Date: 2025-01-18 16:21:25.137931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378ccfd8c886'
down_revision = '3bc4df442391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
